{% set name = "pydantic-zarr" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_zarr-{{ version }}.tar.gz
  sha256: fdb0129722d5a3454f5107de56ec8370a7dc8ccb3fa34f2729632ed4f8da3acd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - zarr >=2.14.2,<3.0.0
    - pydantic >=2.0.0,<3.0.0
    - typing_extensions >=4.7.1,<5.0.0
    - eval-type-backport >=0.1.3,<0.2.0

test:
  imports:
    - pydantic_zarr
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/zarr-developers/pydantic-zarr
  summary: pydantic models for zarr
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - imagejan
    - d-v-b
